### ISSUE TITLE
Missing courses in the generated image

### ISSUE THREAD

**Issue by HaoTian22** [UICHCC/timetable-to-bg#4]
![download](https://github.com/UICHCC/timetable-to-bg/assets/48882584/3ab4efc2-64cd-403b-8163-583226cb8ade)
![image](https://github.com/UICHCC/timetable-to-bg/assets/48882584/ccdf61eb-df7b-4a2f-a346-cb249c9343c0)

Obviously, a lot of courses were missing.
I'm sure that I have copied and pasted the whole table, and the parser in step 1 works well.

![image](https://github.com/UICHCC/timetable-to-bg/assets/48882584/ff049f45-ba64-4c1b-ae13-fe96bfcd4e60)

**Comment by ecwu** [comment]
Could you please save and upload your MIS timetable page as a HTML file here, so we can have a testing sample.

**Comment by HaoTian22** [comment]
[UIC MIS.zip](https://github.com/UICHCC/timetable-to-bg/files/15287009/UIC.MIS.zip)

**Comment by ecwu** [comment]
The root cause for this bug is the original course merge logic can only handle a two hours session, when the course spans three hours, the time merging logic will returns a incorrect structure list.

- What it should look like: `[1,2,3]`
- What it return: `[[1,2],3]`

The new logic will check the length of the array first and apply different merge logic, and the correct image should generates

![image](https://github.com/UICHCC/timetable-to-bg/assets/21114722/b40127c2-d068-4d70-87e1-6698a0b6a65f)
